name: create-release-from-artefact

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: "ID of the macos-universal2 workflow run"
        required: true
      version:
        description: "Version of the release (e.g., 1.20.0)"
        required: true

permissions:
  contents: write
  actions: read

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - name: List available artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Listing artifacts for run ID: ${{ github.event.inputs.workflow_run_id }}"
          gh run view ${{ github.event.inputs.workflow_run_id }} --json artifacts --jq '.artifacts[] | .name'

      - name: Download artifact from another workflow run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.inputs.workflow_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: "onnxruntime-osx-universal2-static_lib-${ONNXRUNTIME_VERSION}.zip"


      - name: Create Release and Upload Asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./onnxruntime-osx-universal2-static_lib-${{ github.event.inputs.version }}.zip"
          tag: v${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}